"""Platform event contracts."""

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class EventType(StrEnum):
    AGENT_REGISTERED = "AgentRegistered"
    AGENT_UPDATED = "AgentUpdated"
    AGENT_DELETED = "AgentDeleted"
    AGENT_HEARTBEAT = "AgentHeartbeat"
    AGENT_STATE_CHANGED = "AgentStateChanged"
    ASSET_CREATED = "AssetCreated"
    ASSET_UPDATED = "AssetUpdated"
    ASSET_SOFT_DELETED = "AssetSoftDeleted"
    ASSET_RELATION_CREATED = "AssetRelationCreated"
    ASSET_DISCOVERED = "AssetDiscovered"
    ASSET_EVIDENCE_LINKED = "AssetEvidenceLinked"
    ASSET_REPORT_LINKED = "AssetReportLinked"
    ASSESSMENT_TASK_CREATED = "AssessmentTaskCreated"
    ASSESSMENT_EXECUTION_STARTED = "AssessmentExecutionStarted"
    ASSESSMENT_EXECUTION_FAILED = "AssessmentExecutionFailed"
    ASSESSMENT_RESULT_NORMALIZED = "AssessmentResultNormalized"
    ASSESSMENT_REPORT_GENERATED = "AssessmentReportGenerated"
    DETECTION_TASK_CREATED = "DetectionTaskCreated"
    DETECTION_EXECUTION_STARTED = "DetectionExecutionStarted"
    DETECTION_EXECUTION_FAILED = "DetectionExecutionFailed"
    DETECTION_RESULT_NORMALIZED = "DetectionResultNormalized"
    SECURITY_EVENT_CREATED = "SecurityEventCreated"
    SECURITY_EVENTS_CORRELATED = "SecurityEventsCorrelated"
    TELEMETRY_TASK_CREATED = "TelemetryTaskCreated"
    TELEMETRY_EXECUTION_STARTED = "TelemetryExecutionStarted"
    TELEMETRY_EXECUTION_COMPLETED = "TelemetryExecutionCompleted"
    TELEMETRY_EXECUTION_FAILED = "TelemetryExecutionFailed"
    TELEMETRY_CHECKPOINT_COMMITTED = "TelemetryCheckpointCommitted"
    TELEMETRY_REPLAY_REQUESTED = "TelemetryReplayRequested"
    TELEMETRY_BACKPRESSURE_APPLIED = "TelemetryBackpressureApplied"
    INCIDENT_CREATED = "IncidentCreated"
    INCIDENT_TRANSITIONED = "IncidentTransitioned"
    INCIDENT_ASSIGNED = "IncidentAssigned"
    INCIDENT_MERGED = "IncidentMerged"
    INCIDENT_ARTIFACT_LINKED = "IncidentArtifactLinked"
    INVESTIGATION_CASE_CREATED = "InvestigationCaseCreated"
    CASE_COMMENT_ADDED = "CaseCommentAdded"
    RESPONSE_PLAN_CREATED = "ResponsePlanCreated"
    RESPONSE_PLAN_APPROVED = "ResponsePlanApproved"
    RESPONSE_PLAN_REJECTED = "ResponsePlanRejected"
    RESPONSE_EXECUTION_STARTED = "ResponseExecutionStarted"
    RESPONSE_EXECUTION_COMPLETED = "ResponseExecutionCompleted"
    RESPONSE_EXECUTION_FAILED = "ResponseExecutionFailed"
    RESPONSE_ROLLBACK_COMPLETED = "ResponseRollbackCompleted"
    NOTIFICATION_PLAN_CREATED = "NotificationPlanCreated"
    NOTIFICATION_SUPPRESSED = "NotificationSuppressed"
    NOTIFICATION_EXECUTION_STARTED = "NotificationExecutionStarted"
    NOTIFICATION_VERIFIED = "NotificationVerified"
    NOTIFICATION_EXECUTION_FAILED = "NotificationExecutionFailed"
    TICKET_CREATED = "TicketCreated"
    TICKET_CLOSED = "TicketClosed"
    PLAYBOOK_CREATED = "PlaybookCreated"
    PLAYBOOK_EXECUTION_STARTED = "PlaybookExecutionStarted"
    PLAYBOOK_STEP_STARTED = "PlaybookStepStarted"
    PLAYBOOK_STEP_COMPLETED = "PlaybookStepCompleted"
    PLAYBOOK_STEP_FAILED = "PlaybookStepFailed"
    PLAYBOOK_EXECUTION_COMPLETED = "PlaybookExecutionCompleted"
    PLAYBOOK_EXECUTION_FAILED = "PlaybookExecutionFailed"
    PLAYBOOK_COMPENSATION_STARTED = "PlaybookCompensationStarted"
    PLAYBOOK_COMPENSATION_COMPLETED = "PlaybookCompensationCompleted"
    WORKER_REGISTERED = "WorkerRegistered"
    WORKER_HEARTBEAT = "WorkerHeartbeat"
    WORKER_STATE_CHANGED = "WorkerStateChanged"
    WORKER_LEASE_ACQUIRED = "WorkerLeaseAcquired"
    WORKER_LEASE_RENEWED = "WorkerLeaseRenewed"
    WORKER_LEASE_RELEASED = "WorkerLeaseReleased"
    WORKER_LEASE_EXPIRED = "WorkerLeaseExpired"
    SANDBOX_EXECUTION_STARTED = "SandboxExecutionStarted"
    SANDBOX_EXECUTION_COMPLETED = "SandboxExecutionCompleted"
    SANDBOX_EXECUTION_FAILED = "SandboxExecutionFailed"
    SANDBOX_EXECUTION_TIMED_OUT = "SandboxExecutionTimedOut"
    SANDBOX_EXECUTION_CANCELLED = "SandboxExecutionCancelled"
    SANDBOX_EXECUTION_RECOVERED = "SandboxExecutionRecovered"
    SECRET_REFERENCE_RESOLVED = "SecretReferenceResolved"
    SECRET_REFERENCE_RESOLVE_FAILED = "SecretReferenceResolveFailed"
    ZAP_SESSION_CREATED = "ZapSessionCreated"
    ZAP_POLICY_ENFORCED = "ZapPolicyEnforced"
    ZAP_EXECUTION_COMPLETED = "ZapExecutionCompleted"
    ZAP_ALERT_NORMALIZED = "ZapAlertNormalized"
    FINDING_CREATED = "FindingCreated"
    FINDING_TRANSITIONED = "FindingTransitioned"
    KNOWLEDGE_IMPORTED = "KnowledgeImported"
    KNOWLEDGE_VERSION_CREATED = "KnowledgeVersionCreated"
    KNOWLEDGE_RELATION_CREATED = "KnowledgeRelationCreated"
    ASSET_KNOWLEDGE_LINKED = "AssetKnowledgeLinked"
    EVIDENCE_KNOWLEDGE_LINKED = "EvidenceKnowledgeLinked"
    REPORT_KNOWLEDGE_LINKED = "ReportKnowledgeLinked"
    TOOL_REGISTERED = "ToolRegistered"
    TOOL_DISABLED = "ToolDisabled"
    TASK_CREATED = "TaskCreated"
    TASK_STATE_CHANGED = "TaskStateChanged"
    TASK_STARTED = "TaskStarted"
    TASK_FINISHED = "TaskFinished"
    TASK_FAILED = "TaskFailed"
    RUNTIME_LOADED = "RuntimeLoaded"
    RUNTIME_STARTED = "RuntimeStarted"
    RUNTIME_STOPPED = "RuntimeStopped"
    RUNTIME_RELOADED = "RuntimeReloaded"
    RUNTIME_DESTROYED = "RuntimeDestroyed"
    RUNTIME_HEALTH_CHECKED = "RuntimeHealthChecked"
    RUNTIME_TASK_STARTED = "RuntimeTaskStarted"
    RUNTIME_TASK_FINISHED = "RuntimeTaskFinished"
    RUNTIME_TASK_FAILED = "RuntimeTaskFailed"
    TOOL_LOADED = "ToolLoaded"
    TOOL_UNLOADED = "ToolUnloaded"
    TOOL_INVOKED = "ToolInvoked"
    EVIDENCE_SAVED = "EvidenceSaved"
    REPORT_GENERATED = "ReportGenerated"
    WORKFLOW_CREATED = "WorkflowCreated"
    WORKFLOW_STARTED = "WorkflowStarted"
    WORKFLOW_STATE_CHANGED = "WorkflowStateChanged"
    WORKFLOW_STEP_STARTED = "WorkflowStepStarted"
    WORKFLOW_STEP_FINISHED = "WorkflowStepFinished"
    WORKFLOW_CANCELLED = "WorkflowCancelled"
    DISPATCH_FAILED = "DispatchFailed"
    PERMISSION_REJECTED = "PermissionRejected"
    VALIDATION_ERROR = "ValidationError"
    UNHANDLED_EXCEPTION = "UnhandledException"


class PlatformEvent(BaseModel):
    """Immutable event envelope consumed through injected event boundaries."""

    id: UUID = Field(default_factory=uuid4)
    type: EventType
    occurred_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    trace_id: str
    aggregate_id: UUID | None = None
    actor: str = "system"
    resource: str
    agent_id: UUID | None = None
    task_id: UUID | None = None
    tool_id: UUID | None = None
    payload: dict[str, Any] = Field(default_factory=dict)
    result: dict[str, Any] | None = None
    error: str | None = None
